Frontend/license search tags
csg-org/CompactConnect pull request #348
Opened 2024-11-19 22:32 UTC by jsandoval81

### Requirements List
- _None_

### Description List
- Add a close (x) icon component
- Add search fields display tag to license list
- Allow the previous search values to be preserved when re-visiting the search form
- Updated the size of the search button to match the updated designs

### Testing List
- `yarn test:unit:all` should run without errors or warnings
- `yarn serve` should run without errors or warnings
- `yarn build` should run without errors or warnings
- Code review
- After searching licensees:
    - If no search terms were requested, display tag does not appear in list view
    - If search terms were requested, display tag should display above table next to search button
    - Search tag should show the requested search values
    - Clicking the X on the tag should take the user back to the search form with previous values cleared out
    - Clicking the Search button should take the user back to the search form preserving the previous values

Closes #312

2024-11-20 22:18 UTC, ChiefStief requested changes
Looks good. I think I would expect tags to be individual for each search term and each handle toggling off individually / not exiting the search screen when done. If we are doing it this way I'm not sure tags is the most intuitive way to get the idea across.

 That being said this is perfectly fine for now and works well other than the space being added before commas

2024-11-20 22:18 UTC, ChiefStief commented on webroot/src/components/Licensee/LicenseeList/LicenseeList.vue
> +                            {{ searchDisplayLastName }}
I cant tell immediately why but there are spaces being added before the commas between term

2024-11-20 22:22 UTC, ChiefStief commented on webroot/src/components/Licensee/LicenseeList/LicenseeList.vue
> +                            {{ searchDisplayLastName }}
It looks like that is a function of having all the terms listed here on separate lines, the white space is bleeding in.

I might make a searchText computed concatenating all these.

2024-11-21 23:13 UTC, ChiefStief approved these changes

2024-11-21 23:28 UTC, jsandoval81 commented
@jlkravitz This is ready for your review.

2024-11-22 16:58 UTC, jlkravitz approved these changes
@isabeleliassen Good to merge once #352 is approved and merged.

2024-11-22 23:25 UTC, isabeleliassen approved these changes

2024-11-22 23:25 UTC, merged