Remove mock resources from persistent stack
csg-org/CompactConnect pull request #421
Opened 2024-12-30 16:48 UTC by landonshumway-ia

This is part two of the mock resource cleanup. Now that the API ands Ingest stacks are no longer referencing the mock data resources, we can safely delete them from the persistent stack.

### Requirements List
- As part of the deployment to the production environment, after the stacks have finished deploying this update, a developer with the proper permissions will need to delete the following tables/buckets manually:

- MockLicenseTable
- LicenseTable
- MockBulkUploadsBucket

### Description List
- Removed mock and deprecated license table resources
- Removed mock uploads bucket references

### Testing List
- local deployment to sandbox environment to ensure stack updates deploy successfully
- Code review

Closes #110

2024-12-30 20:54 UTC, jusdino requested changes
So excited to see the end of these resources. I see a couple of strays that aren't caught in here, though:
- `lambdas/python/delete-objects`
- `lambdas/python/license-data`

2024-12-30 23:02 UTC, jusdino approved these changes

2024-12-30 23:03 UTC, jusdino commented
@jlkravitz ready for you!

2024-12-31 16:14 UTC, jlkravitz approved these changes
@isabeleliassen Good to merge!

2025-01-06 14:59 UTC, isabeleliassen approved these changes

2025-01-06 14:59 UTC, merged