Start a "How We Work" document
csg-org/CompactConnect pull request #99
Opened 2024-07-17 20:00 UTC by waldoj

A great deal more should go into a document like this, but I'd like to start with something that should be documented now, so that we can all be on the same page about norms and expectations for pull requests.

2024-07-17 20:01 UTC, waldoj commented
@jusdino, I'm hoping that you can take a look at this and see if it aligns with how you'd like to be working. And to the extent to which it doesn't, please propose some edits! And then once you and I agree there, @isabeleliassen, you can see what you think of it.

And this could reasonably change within a few sprints, after @jlkravitz gets settled.

2024-07-17 21:34 UTC, jusdino commented
Oh, thank you! We were just discussing items that intersect with this, today. We did decide, with @jlkravitz, to transition to per-feature PR's for now. We also have a story in progress right now to document API design guidelines as well, which will be part of a similar markdown document, as we build up more working conventions.

2024-07-17 21:45 UTC, jusdino requested changes

2024-07-17 21:45 UTC, jusdino commented on HOW_WE_WORK.md
> +InspiringApps will work on their own fork of the repository. They will file a single pull request at the end of each sprint that includes all work completed in that sprint, as presented at the sprint
We did agree to some different practices, as of this morning:

- We will open pull requests for each feature, as they are completed, after we have completed our own QA/review process
- Pull request names should reflect the feature they encapsulate
- We will open pull requests from a feature branch in the IA fork to the `development` branch in the CSG repo
- CSG will periodically merge their `development` branch into `main` to promote updates in their staging (UAT) environment to production

2024-07-18 16:18 UTC, waldoj commented
Great! I've updated the document to reflect that agreement. How does this look, @jusdino?

2024-07-18 21:02 UTC, jusdino commented
Looks great!

2024-07-18 21:08 UTC, jusdino approved these changes

2024-07-19 20:42 UTC, isabeleliassen approved these changes
Looks good to me! We should have a more thorough version of a How We Work document for the team to look at in about a week.

2024-07-22 17:50 UTC, merged